name: bexh-api-aws-lambda CD

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Set Up VirtualEnv
        run: |
          pip3 install pipenv
          make install-dev
      - name: Run Tests
        run: |
          make test
      - name: Create Build Artifact
        run: |
          make clean
          make build
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: bexh-email-aws-lambda-artifact
          path: dist/bexh-email-aws-lambda.zip
      - name: Upload Dist to S3
        uses: jakejarvis/s3-sync-action@master
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_LAMBDA_DEPLOY_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"
          SOURCE_DIR: "dist"
